### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tkellen** [bocoup/learn-ansible#9]
- [x] your-development-server (30 minutes)
- [x] permission-elevation  (15 minutes)
- [x] ansible (10 minutes)
- [x] user-management (15 minutes)
- [x] variables-loops-and-filters (20 minutes)
- [x] tasks-and-idempotency (20 minutes)
- [x] control-flow (30 minutes)
- [x] nginx-up-front (20 minutes)
- [x] services-templates-and-registering-variables (45 minutes)
- [x] your-production-server (1 hour)
- [x] managing-secrets (15 minutes)
